### ISSUE TITLE
Python examples signal names

### ISSUE THREAD

**Issue by gallevatohbk** [openDAQ/openDAQ#425]
In python examples csv_writer and signal_graphed_overtime.py, and maybe others,
signal names are retrieved using "signal.signal_descriptor.name".
However signal_descriptor is not set via streaming protocol (tested with websocket), giving empty name strings

Instead, the names can be retrieved directly from the object "signal.name"

**Comment by JakaMohorkoDS** [comment]
Hello,

Thank you for the observation! Indeed in those examples `signal.name` should be used. The data descriptor name is highly specific and it's only used when we want to explicitly label the data in a signal, or when the signal contains `struct` data.

The field is not mandatory, and as such, cannot be relied upon to be filled in.
