### ISSUE TITLE
Can't install openDAQ after build

### ISSUE THREAD

**Issue by white5354** [openDAQ/openDAQ#499]
When i Building openDAQ™ from source.When after execute `cmake --build .` I meet a problem when i execute `cmake --install . --prefix "openDAQ"`.
 
Below 
![image](https://github.com/user-attachments/assets/d10f675b-a62c-4f7c-915f-06d385c61038)

And I find my file no **Release** file. only Debug file.

**Comment by JakaMohorkoDS** [comment]
Hello, it seems that fmt always tries to install the release target, but the SDK was built in debug. I'd suggest building the SDK in release mode by calling `cmake --build . --config Release`. 

Explicitly specifying the config when installing seems to also work: `cmake --install . --prefix "openDAQ" --config Debug`. The documentation should be updated to clearly reflect the commands.

**Comment by JakaMohorkoDS** [comment]
Addressed in https://github.com/openDAQ/openDAQ/pull/522
