### ISSUE TITLE
No find Devices

### ISSUE THREAD

**Issue by white5354** [openDAQ/openDAQ#504]
Hello, when I follow the documentation [openDAQ™ client application](https://docs.opendaq.com/manual/opendaq/3.0.0/getting_started/quick_start_application.html#own_simulator),I start Virtual box simulator image,below this
![image](https://github.com/user-attachments/assets/1565a120-a610-4f1e-ac86-655cb7764095)

but I note this 
```
import opendaq

# Create an openDAQ(TM) instance
instance = opendaq.Instance()

# Find and output the names and connection strings of all available devices
for device_info in instance.available_devices:
    print("Name:", device_info.name, "Connection string:", device_info.connection_string)
    for capability in device_info.server_capabilities:
        print("Capability:", capability.protocol_name, "Connection string:", capability.connection_string)
```
There are no devices,look below
![image](https://github.com/user-attachments/assets/0f5685e2-9e6b-43c0-9b75-b502d66b3fac)

What did I do wrong?

**Comment by JakaMohorkoDS** [comment]
Note quite sure what you mean by "there are no devices," as the output shows that there are 3 devices found. The "Reference device simulator" has 3 server capabilities, while 2 more devices are simulators that you can add locally (Device 0 and Device 1).

**Comment by white5354** [comment]
@JakaMohorkoDS thx for your reply.Your are right.I just want to get the exports like 
![image](https://github.com/user-attachments/assets/c0e2d0d9-20db-4feb-9595-fbdc7ef43783)
maybe i should believe in code.
